sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - SAUCE_USERNAME=elastic-apm-base
  - SAUCE_ACCESS_KEY=4b6720f1-ecdc-448d-85be-ebf947e14507
  matrix:
  - MODE=saucelabs
cache:
  directories:
  - node_modules
addons:
  firefox: '57.0'
  apt:
    packages:
     - xsltproc
     - libxml2-utils
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3